### ISSUE TITLE
Investigate Wikipedia Dump handeling 

### ISSUE THREAD

**Issue by HughP** [HughP/MLKA-Bash-data#15]
Jon W. suggests that we can be more efficient in the Wikipedia dump handling. Read more on the code example here:

https://github.com/plujon/Bash-data-mlka/commit/4c7b4cd099f12515ecf0d079598582efcf77d52b

**Comment by ghost** [comment]
The problem with a simple command is, one removes the intelligence for checking if each file already exists. A simple mv command stomps on and over writes all the data in Wiki-Data folder. mv works, but it's assuming a lot. lol we didn't call it awesome-script.bash for nothing :) Also currently it takes less than a couple seconds to execute on my Raspberry PI B.

**Comment by HughP** [comment]
That is what I thought when I looked over his code. And why I didn't just copy it in. I am inclined to reject the code suggestion because it does not adequately handle the use case.

**Comment by ghost** [comment]
Agreed :)
