### ISSUE TITLE
Path for $WIKI_LANGUAGES

### ISSUE THREAD

**Issue by ghost** [HughP/MLKA-Bash-data#38]
Line 79 of wikipedia-process.bash
I have yet to test it but on one line there is:

```
"$HOME_FOLDER"/$WIKI_LANGUAGES
```

on the subsequent uses/references only:

```
$WIKI_LANGUAGES
```

is used. Not sure yet how it actually effects it though, just an observation.

**Comment by HughP** [comment]
That is because of where the active command execution is taking place, relative to the other files.
